name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-13  # Use a specific recent macOS version for better pod compatibility
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'  # Use latest stable Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Set iOS deployment target (if not set in Podfile)
        run: |
          sed -i '' 's/^# platform :ios, .*/platform :ios, "12.0"/' ios/Podfile
        # This ensures the platform version is at least 12.0, required by many pods.

      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS App (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA output directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
